name: mht_viewer_app
description: 极简 MHT 文件查看器
publish_to: none
version: 1.0.2+3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  file_picker: ^8.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
